name: hangman
description: "Hangman Game"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  date_format: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1

flutter_app_name:
  name: 'Hangman'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/gallow.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: images/gallow.png
  android_12:
    image: images/gallow.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    android: true
    ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf